# custom colors for factors of specific names.  Each name consists of a
# dictionary of level name / color string pairs.
level_colors:
  Population:
    Bantu: "#ffcc99"
    Mbororo_Fulani: "#999FFF"
    Bagyeli: "#a9315c"
    USA: "#001d73"
    Baka: "#f58aa5"
  Subsistence:
    Agropastoralist: "#ffcc99"
    Pastoralist: "#999FFF"
    Hunter-Gatherer: "#993366"
    Industrial_Agropastoralist: "#001d73"
  Sampling.Site:
    Aviation: "#7d6d00"
    Bidou_I: "#1f47c9"
    Bosquet: "#abd464"
    Missoume: "#c00097"
    Ndtoua: "#006d13"
    Njibot: "#b087ff"
    Nkolbikong: "#ff545b"
    Ntambang: "#00b7e8"
    Sabga: "#624098"

# sampleID will be mapped to this metadata column for display purposes
label_samples_by: "LabID"

# These are the notable metadata variables that Meagan identified
metadata_cols_of_interest:
  - "Sex"
  - "Subsistence"
  - "Sampling.Site"
  - "Total_ANTS"
  - "Population"
  - "HIV_positive_combokitresult"
  - "PosOrNeg_Ascaris"
  - "PosOrNeg_Entamoeba"
  - "PosOrNeg_Giardia"
  - "PosOrNeg_Necator"
  - "PosOrNeg_Strongyloides"
  - "PosOrNeg_Trichuris"
  - "PosOrNeg_PanCrypto"
  - "PosOrNeg_Ancylostoma"
  - "High_Pos_Ascaris"
  - "High_Pos_Entamoeba"
  - "High_Pos_Giardia"
  - "High_Pos_Necator"
  - "High_Pos_Strongyloides"
  - "High_Pos_Trichuris"
  - "High_Pos_Ancylostoma"
  - "High_Pos_Crypto"
  - "ants_binary"
